version: '3.8'
services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - test_work
  api:
    build: ./src
    container_name: api_backend
    environment:
      PORT: 3001
      REDIS_HOST: redis
      REDIS_PORT: 6379
      TRENDING: 'https://trending.bid'
    ports:
      - '3001:3001'
    depends_on:
      - redis
    networks:
      - test_work
networks:
  test_work:
    driver: bridge
